### ISSUE TITLE
Why a fill rate ?

### ISSUE THREAD

**Issue by sebmoine** [Lanelle64/JDLV-Raphael-TD5#8]
Why a filling rate when we define the number of population? If we define the population at 80 on a 10x10 grid, that's already 80%.
For the moment, if we define the population at 80 (10x10 grid) and a fill_rate at 0.6, int he "initilisation()" function we have:
    nb_cell_dep = round(grid.size * fill_rate) #so equal to 60
    nb_cell_dep //= len(total_population) #but here equal to 1

So I dont understand why we need a fill_rate when initializing the population at 80 make it 80%, and if we want to change this rate by 60%, finally we have 1% and then a loop :
        for j in range(nb_cell_dep):
looping inly one time for the value : 0

Afterwards, I don't know this game, maybe I misunderstood something.

**Comment by Lanelle64** [comment]
So the idea is that you chose the quantity of population usually between 1 and 4, because each individual only interacts with other individuals from the same population. Then filling rate is for the board, where each population starts with equal weight.

So for example 2 populations at 0.6 filling rate make a board with 30% tiles occupied by the first population, 30% occupied by the second population, and 40% of the board stays empty. 

I suggest to check the wiki page that I will add a link for in the readme to understand how the game functions.
